<?php

namespace App\Scripts;

class GreatWall_VolexC30_MC9S12HY48_V1 extends Script
{
    public function getResult()
    {
        $hex = $this->getByteForPosition('20', 5) . $this->getByteForPosition('20', 6). $this->getByteForPosition('20', 7);
        $number = hexdec($hex);
         
        return [
            'result' =>round (($number)),
            'image' => 'assets/GreetWall.png',
            'texts' => [
                'Volex C30 V1  ',
                'Micro MC9S12HY48',
                'www.FlashEeprom.com'
            ],
            'fileprefix' => 'flasheeprom'
        ];
    }
    
    public function calculate(int $value)

    {   
        $result = round(($value));
        $hex = str_pad(dechex($result), 6, '0', STR_PAD_LEFT);
       

        return
         [
            ['row' => '10', 'cell' =>13, 'value' => substr($hex, 0, 2)],
            ['row' => '10', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '10', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '20', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '20', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '20', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '30', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '30', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '30', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '40', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '40', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '40', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '50', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '50', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '50', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '60', 'cell' =>13, 'value' => substr($hex, 0, 2)],
            ['row' => '60', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '60', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '70', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '70', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '70', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '80', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '80', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '80', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '90', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '90', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '90', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => 'A0', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => 'A0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => 'A0', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => 'B0', 'cell' =>13, 'value' => substr($hex, 0, 2)],
            ['row' => 'B0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => 'B0', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => 'C0', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => 'C0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => 'C0', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => 'D0', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => 'D0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => 'D0', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => 'E0', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => 'E0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => 'E0', 'cell' => 15, 'value' => substr($hex, 4, 2)],


            ['row' => '20', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '20', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '20', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '30', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '30', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '30', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '40', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '40', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '40', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '50', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '50', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '50', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '60', 'cell' =>5, 'value' => substr($hex, 0, 2)],
            ['row' => '60', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '60', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '70', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '70', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '70', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '80', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '80', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '80', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '90', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '90', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '90', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => 'A0', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => 'A0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => 'A0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => 'B0', 'cell' =>5, 'value' => substr($hex, 0, 2)],
            ['row' => 'B0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => 'B0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => 'C0', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => 'C0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => 'C0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => 'D0', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => 'D0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => 'D0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => 'E0', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => 'E0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => 'E0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => 'F0', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => 'F0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => 'F0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
           
            ['row' => '1A0', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '1A0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '1A0', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '1B0', 'cell' =>13, 'value' => substr($hex, 0, 2)],
            ['row' => '1B0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '1B0', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '1C0', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '1C0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '1C0', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '1D0', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '1D0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '1D0', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '1E0', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '1E0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '1E0', 'cell' => 15, 'value' => substr($hex, 4, 2)],

            ['row' => '1A0', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '1A0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '1A0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '1B0', 'cell' =>5, 'value' => substr($hex, 0, 2)],
            ['row' => '1B0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '1B0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '1C0', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '1C0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '1C0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '1D0', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '1D0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '1D0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '1E0', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '1E0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '1E0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '1F0', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '1F0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '1F0', 'cell' => 7, 'value' => substr($hex, 4, 2)],

            ['row' => '240', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '240', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '240', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '250', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '250', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '250', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '260', 'cell' =>5, 'value' => substr($hex, 0, 2)],
            ['row' => '260', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '260', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '270', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '270', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '270', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '280', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '280', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '280', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '290', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '290', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '290', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '2A0', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '2A0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '2A0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '2B0', 'cell' =>5, 'value' => substr($hex, 0, 2)],
            ['row' => '2B0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '2B0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '2C0', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '2C0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '2C0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '2D0', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '2D0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '2D0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '2E0', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '2E0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '2E0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '2F0', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '2F0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '2F0', 'cell' => 7, 'value' => substr($hex, 4, 2)],

            ['row' => '240', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '240', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '240', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '250', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '250', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '250', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '260', 'cell' =>13, 'value' => substr($hex, 0, 2)],
            ['row' => '260', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '260', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '270', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '270', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '270', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '280', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '280', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '280', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '290', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '290', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '290', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '2A0', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '2A0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '2A0', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '2B0', 'cell' =>13, 'value' => substr($hex, 0, 2)],
            ['row' => '2B0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '2B0', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '2C0', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '2C0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '2C0', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '2D0', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '2D0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '2D0', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '2E0', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '2E0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '2E0', 'cell' => 15, 'value' => substr($hex, 4, 2)],


            ['row' => '320', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '320', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '320', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '330', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '330', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '330', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '340', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '340', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '340', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '350', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '350', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '350', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '360', 'cell' =>13, 'value' => substr($hex, 0, 2)],
            ['row' => '360', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '360', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '370', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '370', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '370', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '380', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '380', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '380', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '390', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '390', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '390', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '3A0', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '3A0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '3A0', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '3B0', 'cell' =>13, 'value' => substr($hex, 0, 2)],
            ['row' => '3B0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '3B0', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '3C0', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '3C0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '3C0', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '3D0', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '3D0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '3D0', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '3E0', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '3E0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '3E0', 'cell' => 15, 'value' => substr($hex, 4, 2)],


            ['row' => '330', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '330', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '330', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '340', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '340', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '340', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '350', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '350', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '350', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '360', 'cell' =>5, 'value' => substr($hex, 0, 2)],
            ['row' => '360', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '360', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '370', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '370', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '370', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '380', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '380', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '380', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '390', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '390', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '390', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '3A0', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '3A0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '3A0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '3B0', 'cell' =>5, 'value' => substr($hex, 0, 2)],
            ['row' => '3B0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '3B0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '3C0', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '3C0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '3C0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '3D0', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '3D0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '3D0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '3E0', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '3E0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '3E0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '3F0', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '3F0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '3F0', 'cell' => 7, 'value' => substr($hex, 4, 2)],

            
            ['row' => '400', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '400', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '400', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '410', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '410', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '410', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '420', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '420', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '420', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '430', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '430', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '430', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '440', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '440', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '440', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '450', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '450', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '450', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '460', 'cell' =>5, 'value' => substr($hex, 0, 2)],
            ['row' => '460', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '460', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '470', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '470', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '470', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '480', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '480', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '480', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '490', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '490', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '490', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '4A0', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '4A0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '4A0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '4B0', 'cell' =>5, 'value' => substr($hex, 0, 2)],
            ['row' => '4B0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '4B0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '4C0', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '4C0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '4C0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '4D0', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '4D0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '4D0', 'cell' => 7, 'value' => substr($hex, 4, 2)],
            ['row' => '4E0', 'cell' => 5, 'value' => substr($hex, 0, 2)],
            ['row' => '4E0', 'cell' => 6, 'value' => substr($hex, 2, 2)],
            ['row' => '4E0', 'cell' => 7, 'value' => substr($hex, 4, 2)],

            ['row' => '400', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '400', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '400', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '410', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '410', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '410', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '420', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '420', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '420', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '430', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '430', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '430', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '440', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '440', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '440', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '450', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '450', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '450', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '460', 'cell' =>13, 'value' => substr($hex, 0, 2)],
            ['row' => '460', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '460', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '470', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '470', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '470', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '480', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '480', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '480', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '490', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '490', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '490', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '4A0', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '4A0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '4A0', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '4B0', 'cell' =>13, 'value' => substr($hex, 0, 2)],
            ['row' => '4B0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '4B0', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '4C0', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '4C0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '4C0', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '4D0', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '4D0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '4D0', 'cell' => 15, 'value' => substr($hex, 4, 2)],
            ['row' => '4E0', 'cell' => 13, 'value' => substr($hex, 0, 2)],
            ['row' => '4E0', 'cell' => 14, 'value' => substr($hex, 2, 2)],
            ['row' => '4E0', 'cell' => 15, 'value' => substr($hex, 4, 2)],
        ];
    }
}
