<?php

namespace App\Scripts;

class  Mercedes_AW_168_68HC11KH4 extends Script
{
    public function getResult()
    {
        $hex = $this->getByteForPosition('90',0). $this->getByteForPosition('90', 1) . $this->getByteForPosition('90',2). $this->getByteForPosition('90',3);
        $number = hexdec($hex);
         
        return [
            'result' => round($number),
            'image' => 'assets/Mercedes.png',
            'texts' => [
                'AW 168',
                'Micro 68hc711KG4',
                'www.FlashEeprom.com'
            ],
            'fileprefix' => 'flasheeprom'
        ];
    }
    
    public function calculate(int $value)
    {   $result = round(($value));
        $hex = str_pad(dechex($result), 8, '0', STR_PAD_LEFT);

        $result2 = round(4294967295-($value));
        $hex2 = str_pad(dechex($result2), 8, '0', STR_PAD_LEFT);

        
        return
         [
            

            ['row' => '80', 'cell' => 0, 'value' => substr($hex, 0, 2)],
            ['row' => '80', 'cell' => 1, 'value' => substr($hex, 2, 2)],
            ['row' => '80', 'cell' => 2, 'value' => substr($hex, 4, 2)],
            ['row' => '80', 'cell' => 3, 'value' => substr($hex, 6, 2)],
            ['row' => '80', 'cell' => 4, 'value' => substr($hex, 0, 2)],
            ['row' => '80', 'cell' => 5, 'value' => substr($hex, 2, 2)],
            ['row' => '80', 'cell' => 6, 'value' => substr($hex, 4, 2)],
            ['row' => '80', 'cell' => 7, 'value' => substr($hex, 6, 2)],
            ['row' => '80', 'cell' => 8, 'value' => substr($hex, 0, 2)],
            ['row' => '80', 'cell' => 9, 'value' => substr($hex, 2, 2)],
            ['row' => '80', 'cell' => 10, 'value' => substr($hex, 4, 2)],
            ['row' => '80', 'cell' => 11, 'value' => substr($hex, 6, 2)],
            ['row' => '80', 'cell' => 12, 'value' => substr($hex, 0, 2)],
            ['row' => '80', 'cell' => 13, 'value' => substr($hex, 2, 2)],
            ['row' => '80', 'cell' => 14, 'value' => substr($hex, 4, 2)],
            ['row' => '80', 'cell' => 15, 'value' => substr($hex, 6, 2)],

            ['row' => '90', 'cell' => 0, 'value' => substr($hex, 0, 2)],
            ['row' => '90', 'cell' => 1, 'value' => substr($hex, 2, 2)],
            ['row' => '90', 'cell' => 2, 'value' => substr($hex, 4, 2)],
            ['row' => '90', 'cell' => 3, 'value' => substr($hex, 6, 2)],
            ['row' => '90', 'cell' => 4, 'value' => substr($hex, 0, 2)],
            ['row' => '90', 'cell' => 5, 'value' => substr($hex, 2, 2)],
            ['row' => '90', 'cell' => 6, 'value' => substr($hex, 4, 2)],
            ['row' => '90', 'cell' => 7, 'value' => substr($hex, 6, 2)],
            ['row' => '90', 'cell' => 8, 'value' => substr($hex, 0, 2)],
            ['row' => '90', 'cell' => 9, 'value' => substr($hex, 2, 2)],
            ['row' => '90', 'cell' => 10, 'value' => substr($hex, 4, 2)],
            ['row' => '90', 'cell' => 11, 'value' => substr($hex, 6, 2)],
            ['row' => '90', 'cell' => 12, 'value' => substr($hex, 0, 2)],
            ['row' => '90', 'cell' => 13, 'value' => substr($hex, 2, 2)],
            ['row' => '90', 'cell' => 14, 'value' => substr($hex, 4, 2)],
            ['row' => '90', 'cell' => 15, 'value' => substr($hex, 6, 2)],

            ['row' => 'A0', 'cell' => 0, 'value' => substr($hex, 0, 2)],
            ['row' => 'A0', 'cell' => 1, 'value' => substr($hex, 2, 2)],
            ['row' => 'A0', 'cell' => 2, 'value' => substr($hex, 4, 2)],
            ['row' => 'A0', 'cell' => 3, 'value' => substr($hex, 6, 2)],
            ['row' => 'A0', 'cell' => 4, 'value' => substr($hex, 0, 2)],
            ['row' => 'A0', 'cell' => 5, 'value' => substr($hex, 2, 2)],
            ['row' => 'A0', 'cell' => 6, 'value' => substr($hex, 4, 2)],
            ['row' => 'A0', 'cell' => 7, 'value' => substr($hex, 6, 2)],
            ['row' => 'A0', 'cell' => 8, 'value' => substr($hex, 0, 2)],
            ['row' => 'A0', 'cell' => 9, 'value' => substr($hex, 2, 2)],
            ['row' => 'A0', 'cell' => 10, 'value' => substr($hex, 4, 2)],
            ['row' => 'A0', 'cell' => 11, 'value' => substr($hex, 6, 2)],
            ['row' => 'A0', 'cell' => 12, 'value' => substr($hex, 0, 2)],
            ['row' => 'A0', 'cell' => 13, 'value' => substr($hex, 2, 2)],
            ['row' => 'A0', 'cell' => 14, 'value' => substr($hex, 4, 2)],
            ['row' => 'A0', 'cell' => 15, 'value' => substr($hex, 6, 2)],

            ['row' => 'B0', 'cell' => 0, 'value' => substr($hex, 0, 2)],
            ['row' => 'B0', 'cell' => 1, 'value' => substr($hex, 2, 2)],
            ['row' => 'B0', 'cell' => 2, 'value' => substr($hex, 4, 2)],
            ['row' => 'B0', 'cell' => 3, 'value' => substr($hex, 6, 2)],
            ['row' => 'B0', 'cell' => 4, 'value' => substr($hex, 0, 2)],
            ['row' => 'B0', 'cell' => 5, 'value' => substr($hex, 2, 2)],
            ['row' => 'B0', 'cell' => 6, 'value' => substr($hex, 4, 2)],
            ['row' => 'B0', 'cell' => 7, 'value' => substr($hex, 6, 2)],
            ['row' => 'B0', 'cell' => 8, 'value' => substr($hex, 0, 2)],
            ['row' => 'B0', 'cell' => 9, 'value' => substr($hex, 2, 2)],
            ['row' => 'B0', 'cell' => 10, 'value' => substr($hex, 4, 2)],
            ['row' => 'B0', 'cell' => 11, 'value' => substr($hex, 6, 2)],
            ['row' => 'B0', 'cell' => 12, 'value' => substr($hex, 0, 2)],
            ['row' => 'B0', 'cell' => 13, 'value' => substr($hex, 2, 2)],
            ['row' => 'B0', 'cell' => 14, 'value' => substr($hex, 4, 2)],
            ['row' => 'B0', 'cell' => 15, 'value' => substr($hex, 6, 2)],

            ['row' => 'C0', 'cell' => 0, 'value' => substr($hex, 0, 2)],
            ['row' => 'C0', 'cell' => 1, 'value' => substr($hex, 2, 2)],
            ['row' => 'C0', 'cell' => 2, 'value' => substr($hex, 4, 2)],
            ['row' => 'C0', 'cell' => 3, 'value' => substr($hex, 6, 2)],
            ['row' => 'C0', 'cell' => 4, 'value' => substr($hex, 0, 2)],
            ['row' => 'C0', 'cell' => 5, 'value' => substr($hex, 2, 2)],
            ['row' => 'C0', 'cell' => 6, 'value' => substr($hex, 4, 2)],
            ['row' => 'C0', 'cell' => 7, 'value' => substr($hex, 6, 2)],
            ['row' => 'C0', 'cell' => 8, 'value' => substr($hex, 0, 2)],
            ['row' => 'C0', 'cell' => 9, 'value' => substr($hex, 2, 2)],
            ['row' => 'C0', 'cell' => 10, 'value' => substr($hex, 4, 2)],
            ['row' => 'C0', 'cell' => 11, 'value' => substr($hex, 6, 2)],
            ['row' => 'C0', 'cell' => 12, 'value' => substr($hex, 0, 2)],
            ['row' => 'C0', 'cell' => 13, 'value' => substr($hex, 2, 2)],
            ['row' => 'C0', 'cell' => 14, 'value' => substr($hex, 4, 2)],
            ['row' => 'C0', 'cell' => 15, 'value' => substr($hex, 6, 2)],

            ['row' => 'D0', 'cell' => 0, 'value' => substr($hex, 0, 2)],
            ['row' => 'D0', 'cell' => 1, 'value' => substr($hex, 2, 2)],
            ['row' => 'D0', 'cell' => 2, 'value' => substr($hex, 4, 2)],
            ['row' => 'D0', 'cell' => 3, 'value' => substr($hex, 6, 2)],
            ['row' => 'D0', 'cell' => 4, 'value' => substr($hex, 0, 2)],
            ['row' => 'D0', 'cell' => 5, 'value' => substr($hex, 2, 2)],
            ['row' => 'D0', 'cell' => 6, 'value' => substr($hex, 4, 2)],
            ['row' => 'D0', 'cell' => 7, 'value' => substr($hex, 6, 2)],
            ['row' => 'D0', 'cell' => 8, 'value' => substr($hex, 0, 2)],
            ['row' => 'D0', 'cell' => 9, 'value' => substr($hex, 2, 2)],
            ['row' => 'D0', 'cell' => 10, 'value' => substr($hex, 4, 2)],
            ['row' => 'D0', 'cell' => 11, 'value' => substr($hex, 6, 2)],
            ['row' => 'D0', 'cell' => 12, 'value' => substr($hex, 0, 2)],
            ['row' => 'D0', 'cell' => 13, 'value' => substr($hex, 2, 2)],
            ['row' => 'D0', 'cell' => 14, 'value' => substr($hex, 4, 2)],
            ['row' => 'D0', 'cell' => 15, 'value' => substr($hex, 6, 2)],

            ['row' => 'E0', 'cell' => 0, 'value' => substr($hex, 0, 2)],
            ['row' => 'E0', 'cell' => 1, 'value' => substr($hex, 2, 2)],
            ['row' => 'E0', 'cell' => 2, 'value' => substr($hex, 4, 2)],
            ['row' => 'E0', 'cell' => 3, 'value' => substr($hex, 6, 2)],
            ['row' => 'E0', 'cell' => 4, 'value' => substr($hex, 0, 2)],
            ['row' => 'E0', 'cell' => 5, 'value' => substr($hex, 2, 2)],
            ['row' => 'E0', 'cell' => 6, 'value' => substr($hex, 4, 2)],
            ['row' => 'E0', 'cell' => 7, 'value' => substr($hex, 6, 2)],
            ['row' => 'E0', 'cell' => 8, 'value' => substr($hex, 0, 2)],
            ['row' => 'E0', 'cell' => 9, 'value' => substr($hex, 2, 2)],
            ['row' => 'E0', 'cell' => 10, 'value' => substr($hex, 4, 2)],
            ['row' => 'E0', 'cell' => 11, 'value' => substr($hex, 6, 2)],
            ['row' => 'E0', 'cell' => 12, 'value' => substr($hex, 0, 2)],
            ['row' => 'E0', 'cell' => 13, 'value' => substr($hex, 2, 2)],
            ['row' => 'E0', 'cell' => 14, 'value' => substr($hex, 4, 2)],
            ['row' => 'E0', 'cell' => 15, 'value' => substr($hex, 6, 2)],

            ['row' => 'F0', 'cell' => 0, 'value' => substr($hex, 0, 2)],
            ['row' => 'F0', 'cell' => 1, 'value' => substr($hex, 2, 2)],
            ['row' => 'F0', 'cell' => 2, 'value' => substr($hex, 4, 2)],
            ['row' => 'F0', 'cell' => 3, 'value' => substr($hex, 6, 2)],
            ['row' => 'F0', 'cell' => 4, 'value' => substr($hex, 0, 2)],
            ['row' => 'F0', 'cell' => 5, 'value' => substr($hex, 2, 2)],
            ['row' => 'F0', 'cell' => 6, 'value' => substr($hex, 4, 2)],
            ['row' => 'F0', 'cell' => 7, 'value' => substr($hex, 6, 2)],
            ['row' => 'F0', 'cell' => 8, 'value' => substr($hex, 0, 2)],
            ['row' => 'F0', 'cell' => 9, 'value' => substr($hex, 2, 2)],
            ['row' => 'F0', 'cell' => 10, 'value' => substr($hex, 4, 2)],
            ['row' => 'F0', 'cell' => 11, 'value' => substr($hex, 6, 2)],
            ['row' => 'F0', 'cell' => 12, 'value' => substr($hex, 0, 2)],
            ['row' => 'F0', 'cell' => 13, 'value' => substr($hex, 2, 2)],
            ['row' => 'F0', 'cell' => 14, 'value' => substr($hex, 4, 2)],
            ['row' => 'F0', 'cell' => 15, 'value' => substr($hex, 6, 2)],

            ['row' => '100', 'cell' => 0, 'value' => substr($hex, 0, 2)],
            ['row' => '100', 'cell' => 1, 'value' => substr($hex, 2, 2)],
            ['row' => '100', 'cell' => 2, 'value' => substr($hex, 4, 2)],
            ['row' => '100', 'cell' => 3, 'value' => substr($hex, 6, 2)],
            ['row' => '100', 'cell' => 4, 'value' => substr($hex, 0, 2)],
            ['row' => '100', 'cell' => 5, 'value' => substr($hex, 2, 2)],
            ['row' => '100', 'cell' => 6, 'value' => substr($hex, 4, 2)],
            ['row' => '100', 'cell' => 7, 'value' => substr($hex, 6, 2)],
            ['row' => '100', 'cell' => 8, 'value' => substr($hex, 0, 2)],
            ['row' => '100', 'cell' => 9, 'value' => substr($hex, 2, 2)],
            ['row' => '100', 'cell' => 10, 'value' => substr($hex, 4, 2)],
            ['row' => '100', 'cell' => 11, 'value' => substr($hex, 6, 2)],
            ['row' => '100', 'cell' => 12, 'value' => substr($hex, 0, 2)],
            ['row' => '100', 'cell' => 13, 'value' => substr($hex, 2, 2)],
            ['row' => '100', 'cell' => 14, 'value' => substr($hex, 4, 2)],
            ['row' => '100', 'cell' => 15, 'value' => substr($hex, 6, 2)],

            ['row' => '110', 'cell' => 0, 'value' => substr($hex, 0, 2)],
            ['row' => '110', 'cell' => 1, 'value' => substr($hex, 2, 2)],
            ['row' => '110', 'cell' => 2, 'value' => substr($hex, 4, 2)],
            ['row' => '110', 'cell' => 3, 'value' => substr($hex, 6, 2)],
            ['row' => '110', 'cell' => 4, 'value' => substr($hex, 0, 2)],
            ['row' => '110', 'cell' => 5, 'value' => substr($hex, 2, 2)],
            ['row' => '110', 'cell' => 6, 'value' => substr($hex, 4, 2)],
            ['row' => '110', 'cell' => 7, 'value' => substr($hex, 6, 2)],
            ['row' => '110', 'cell' => 8, 'value' => substr($hex, 0, 2)],
            ['row' => '110', 'cell' => 9, 'value' => substr($hex, 2, 2)],
            ['row' => '110', 'cell' => 10, 'value' => substr($hex, 4, 2)],
            ['row' => '110', 'cell' => 11, 'value' => substr($hex, 6, 2)],
            ['row' => '110', 'cell' => 12, 'value' => substr($hex, 0, 2)],
            ['row' => '110', 'cell' => 13, 'value' => substr($hex, 2, 2)],
            ['row' => '110', 'cell' => 14, 'value' => substr($hex, 4, 2)],
            ['row' => '110', 'cell' => 15, 'value' => substr($hex, 6, 2)],
            
            ['row' => '120', 'cell' => 0, 'value' => substr($hex, 0, 2)],
            ['row' => '120', 'cell' => 1, 'value' => substr($hex, 2, 2)],
            ['row' => '120', 'cell' => 2, 'value' => substr($hex, 4, 2)],
            ['row' => '120', 'cell' => 3, 'value' => substr($hex, 6, 2)],
            ['row' => '120', 'cell' => 4, 'value' => substr($hex, 0, 2)],
            ['row' => '120', 'cell' => 5, 'value' => substr($hex, 2, 2)],
            ['row' => '120', 'cell' => 6, 'value' => substr($hex, 4, 2)],
            ['row' => '120', 'cell' => 7, 'value' => substr($hex, 6, 2)],
            ['row' => '120', 'cell' => 8, 'value' => substr($hex, 0, 2)],
            ['row' => '120', 'cell' => 9, 'value' => substr($hex, 2, 2)],
            ['row' => '120', 'cell' => 10, 'value' => substr($hex, 4, 2)],
            ['row' => '120', 'cell' => 11, 'value' => substr($hex, 6, 2)],
            ['row' => '120', 'cell' => 12, 'value' => substr($hex, 0, 2)],
            ['row' => '120', 'cell' => 13, 'value' => substr($hex, 2, 2)],
            ['row' => '120', 'cell' => 14, 'value' => substr($hex, 4, 2)],
            ['row' => '120', 'cell' => 15, 'value' => substr($hex, 6, 2)],

            ['row' => '130', 'cell' => 0, 'value' => substr($hex, 0, 2)],
            ['row' => '130', 'cell' => 1, 'value' => substr($hex, 2, 2)],
            ['row' => '130', 'cell' => 2, 'value' => substr($hex, 4, 2)],
            ['row' => '130', 'cell' => 3, 'value' => substr($hex, 6, 2)],
            ['row' => '130', 'cell' => 4, 'value' => substr($hex, 0, 2)],
            ['row' => '130', 'cell' => 5, 'value' => substr($hex, 2, 2)],
            ['row' => '130', 'cell' => 6, 'value' => substr($hex, 4, 2)],
            ['row' => '130', 'cell' => 7, 'value' => substr($hex, 6, 2)],
            ['row' => '130', 'cell' => 8, 'value' => substr($hex, 0, 2)],
            ['row' => '130', 'cell' => 9, 'value' => substr($hex, 2, 2)],
            ['row' => '130', 'cell' => 10, 'value' => substr($hex, 4, 2)],
            ['row' => '130', 'cell' => 11, 'value' => substr($hex, 6, 2)],
            ['row' => '130', 'cell' => 12, 'value' => substr($hex, 0, 2)],
            ['row' => '130', 'cell' => 13, 'value' => substr($hex, 2, 2)],
            ['row' => '130', 'cell' => 14, 'value' => substr($hex, 4, 2)],
            ['row' => '130', 'cell' => 15, 'value' => substr($hex, 6, 2)],
            
            ['row' => '140', 'cell' => 0, 'value' => substr($hex, 0, 2)],
            ['row' => '140', 'cell' => 1, 'value' => substr($hex, 2, 2)],
            ['row' => '140', 'cell' => 2, 'value' => substr($hex, 4, 2)],
            ['row' => '140', 'cell' => 3, 'value' => substr($hex, 6, 2)],
            ['row' => '140', 'cell' => 4, 'value' => substr($hex, 0, 2)],
            ['row' => '140', 'cell' => 5, 'value' => substr($hex, 2, 2)],
            ['row' => '140', 'cell' => 6, 'value' => substr($hex, 4, 2)],
            ['row' => '140', 'cell' => 7, 'value' => substr($hex, 6, 2)],


            ['row' => '140', 'cell' => 8, 'value' => substr($hex2, 0, 2)],
            ['row' => '140', 'cell' => 9, 'value' => substr($hex2, 2, 2)],
            ['row' => '140', 'cell' => 10, 'value' => substr($hex2, 4, 2)],
            ['row' => '140', 'cell' => 11, 'value' => substr($hex2, 6, 2)],
            ['row' => '140', 'cell' => 12, 'value' => substr($hex2, 0, 2)],
            ['row' => '140', 'cell' => 13, 'value' => substr($hex2, 2, 2)],
            ['row' => '140', 'cell' => 14, 'value' => substr($hex2, 4, 2)],
            ['row' => '140', 'cell' => 15, 'value' => substr($hex2, 6, 2)],

            ['row' => '150', 'cell' => 0, 'value' => substr($hex2, 0, 2)],
            ['row' => '150', 'cell' => 1, 'value' => substr($hex2, 2, 2)],
            ['row' => '150', 'cell' => 2, 'value' => substr($hex2, 4, 2)],
            ['row' => '150', 'cell' => 3, 'value' => substr($hex2, 6, 2)],
            ['row' => '150', 'cell' => 4, 'value' => substr($hex2, 0, 2)],
            ['row' => '150', 'cell' => 5, 'value' => substr($hex2, 2, 2)],
            ['row' => '150', 'cell' => 6, 'value' => substr($hex2, 4, 2)],
            ['row' => '150', 'cell' => 7, 'value' => substr($hex2, 6, 2)],
            ['row' => '150', 'cell' => 8, 'value' => substr($hex2, 0, 2)],
            ['row' => '150', 'cell' => 9, 'value' => substr($hex2, 2, 2)],
            ['row' => '150', 'cell' => 10, 'value' => substr($hex2, 4, 2)],
            ['row' => '150', 'cell' => 11, 'value' => substr($hex2, 6, 2)],
            ['row' => '150', 'cell' => 12, 'value' => substr($hex2, 0, 2)],
            ['row' => '150', 'cell' => 13, 'value' => substr($hex2, 2, 2)],
            ['row' => '150', 'cell' => 14, 'value' => substr($hex2, 4, 2)],
            ['row' => '150', 'cell' => 15, 'value' => substr($hex2, 6, 2)],

            ['row' => '160', 'cell' => 0, 'value' => substr($hex2, 0, 2)],
            ['row' => '160', 'cell' => 1, 'value' => substr($hex2, 2, 2)],
            ['row' => '160', 'cell' => 2, 'value' => substr($hex2, 4, 2)],
            ['row' => '160', 'cell' => 3, 'value' => substr($hex2, 6, 2)],
            ['row' => '160', 'cell' => 4, 'value' => substr($hex2, 0, 2)],
            ['row' => '160', 'cell' => 5, 'value' => substr($hex2, 2, 2)],
            ['row' => '160', 'cell' => 6, 'value' => substr($hex2, 4, 2)],
            ['row' => '160', 'cell' => 7, 'value' => substr($hex2, 6, 2)],
            ['row' => '160', 'cell' => 8, 'value' => substr($hex2, 0, 2)],
            ['row' => '160', 'cell' => 9, 'value' => substr($hex2, 2, 2)],
            ['row' => '160', 'cell' => 10, 'value' => substr($hex2, 4, 2)],
            ['row' => '160', 'cell' => 11, 'value' => substr($hex2, 6, 2)],
            ['row' => '160', 'cell' => 12, 'value' => substr($hex2, 0, 2)],
            ['row' => '160', 'cell' => 13, 'value' => substr($hex2, 2, 2)],
            ['row' => '160', 'cell' => 14, 'value' => substr($hex2, 4, 2)],
            ['row' => '160', 'cell' => 15, 'value' => substr($hex2, 6, 2)],

            ['row' => '170', 'cell' => 0, 'value' => substr($hex2, 0, 2)],
            ['row' => '170', 'cell' => 1, 'value' => substr($hex2, 2, 2)],
            ['row' => '170', 'cell' => 2, 'value' => substr($hex2, 4, 2)],
            ['row' => '170', 'cell' => 3, 'value' => substr($hex2, 6, 2)],
            ['row' => '170', 'cell' => 4, 'value' => substr($hex2, 0, 2)],
            ['row' => '170', 'cell' => 5, 'value' => substr($hex2, 2, 2)],
            ['row' => '170', 'cell' => 6, 'value' => substr($hex2, 4, 2)],
            ['row' => '170', 'cell' => 7, 'value' => substr($hex2, 6, 2)],
            ['row' => '170', 'cell' => 8, 'value' => substr($hex2, 0, 2)],
            ['row' => '170', 'cell' => 9, 'value' => substr($hex2, 2, 2)],
            ['row' => '170', 'cell' => 10, 'value' => substr($hex2, 4, 2)],
            ['row' => '170', 'cell' => 11, 'value' => substr($hex2, 6, 2)],
            ['row' => '170', 'cell' => 12, 'value' => substr($hex2, 0, 2)],
            ['row' => '170', 'cell' => 13, 'value' => substr($hex2, 2, 2)],
            ['row' => '170', 'cell' => 14, 'value' => substr($hex2, 4, 2)],
            ['row' => '170', 'cell' => 15, 'value' => substr($hex2, 6, 2)],

            ['row' => '180', 'cell' => 0, 'value' => substr($hex2, 0, 2)],
            ['row' => '180', 'cell' => 1, 'value' => substr($hex2, 2, 2)],
            ['row' => '180', 'cell' => 2, 'value' => substr($hex2, 4, 2)],
            ['row' => '180', 'cell' => 3, 'value' => substr($hex2, 6, 2)],
            ['row' => '180', 'cell' => 4, 'value' => substr($hex2, 0, 2)],
            ['row' => '180', 'cell' => 5, 'value' => substr($hex2, 2, 2)],
            ['row' => '180', 'cell' => 6, 'value' => substr($hex2, 4, 2)],
            ['row' => '180', 'cell' => 7, 'value' => substr($hex2, 6, 2)],
            ['row' => '180', 'cell' => 8, 'value' => substr($hex2, 0, 2)],
            ['row' => '180', 'cell' => 9, 'value' => substr($hex2, 2, 2)],
            ['row' => '180', 'cell' => 10, 'value' => substr($hex2, 4, 2)],
            ['row' => '180', 'cell' => 11, 'value' => substr($hex2, 6, 2)],
            ['row' => '180', 'cell' => 12, 'value' => substr($hex2, 0, 2)],
            ['row' => '180', 'cell' => 13, 'value' => substr($hex2, 2, 2)],
            ['row' => '180', 'cell' => 14, 'value' => substr($hex2, 4, 2)],
            ['row' => '180', 'cell' => 15, 'value' => substr($hex2, 6, 2)],

            ['row' => '190', 'cell' => 0, 'value' => substr($hex2, 0, 2)],
            ['row' => '190', 'cell' => 1, 'value' => substr($hex2, 2, 2)],
            ['row' => '190', 'cell' => 2, 'value' => substr($hex2, 4, 2)],
            ['row' => '190', 'cell' => 3, 'value' => substr($hex2, 6, 2)],
            ['row' => '190', 'cell' => 4, 'value' => substr($hex2, 0, 2)],
            ['row' => '190', 'cell' => 5, 'value' => substr($hex2, 2, 2)],
            ['row' => '190', 'cell' => 6, 'value' => substr($hex2, 4, 2)],
            ['row' => '190', 'cell' => 7, 'value' => substr($hex2, 6, 2)],
            ['row' => '190', 'cell' => 8, 'value' => substr($hex2, 0, 2)],
            ['row' => '190', 'cell' => 9, 'value' => substr($hex2, 2, 2)],
            ['row' => '190', 'cell' => 10, 'value' => substr($hex2, 4, 2)],
            ['row' => '190', 'cell' => 11, 'value' => substr($hex2, 6, 2)],
            ['row' => '190', 'cell' => 12, 'value' => substr($hex2, 0, 2)],
            ['row' => '190', 'cell' => 13, 'value' => substr($hex2, 2, 2)],
            ['row' => '190', 'cell' => 14, 'value' => substr($hex2, 4, 2)],
            ['row' => '190', 'cell' => 15, 'value' => substr($hex2, 6, 2)],

            ['row' => '1A0', 'cell' => 0, 'value' => substr($hex2, 0, 2)],
            ['row' => '1A0', 'cell' => 1, 'value' => substr($hex2, 2, 2)],
            ['row' => '1A0', 'cell' => 2, 'value' => substr($hex2, 4, 2)],
            ['row' => '1A0', 'cell' => 3, 'value' => substr($hex2, 6, 2)],
            ['row' => '1A0', 'cell' => 4, 'value' => substr($hex2, 0, 2)],
            ['row' => '1A0', 'cell' => 5, 'value' => substr($hex2, 2, 2)],
            ['row' => '1A0', 'cell' => 6, 'value' => substr($hex2, 4, 2)],
            ['row' => '1A0', 'cell' => 7, 'value' => substr($hex2, 6, 2)],
            ['row' => '1A0', 'cell' => 8, 'value' => substr($hex2, 0, 2)],
            ['row' => '1A0', 'cell' => 9, 'value' => substr($hex2, 2, 2)],
            ['row' => '1A0', 'cell' => 10, 'value' => substr($hex2, 4, 2)],
            ['row' => '1A0', 'cell' => 11, 'value' => substr($hex2, 6, 2)],
            ['row' => '1A0', 'cell' => 12, 'value' => substr($hex2, 0, 2)],
            ['row' => '1A0', 'cell' => 13, 'value' => substr($hex2, 2, 2)],
            ['row' => '1A0', 'cell' => 14, 'value' => substr($hex2, 4, 2)],
            ['row' => '1A0', 'cell' => 15, 'value' => substr($hex2, 6, 2)],

            ['row' => '1B0', 'cell' => 0, 'value' => substr($hex2, 0, 2)],
            ['row' => '1B0', 'cell' => 1, 'value' => substr($hex2, 2, 2)],
            ['row' => '1B0', 'cell' => 2, 'value' => substr($hex2, 4, 2)],
            ['row' => '1B0', 'cell' => 3, 'value' => substr($hex2, 6, 2)],
            ['row' => '1B0', 'cell' => 4, 'value' => substr($hex2, 0, 2)],
            ['row' => '1B0', 'cell' => 5, 'value' => substr($hex2, 2, 2)],
            ['row' => '1B0', 'cell' => 6, 'value' => substr($hex2, 4, 2)],
            ['row' => '1B0', 'cell' => 7, 'value' => substr($hex2, 6, 2)],
            ['row' => '1B0', 'cell' => 8, 'value' => substr($hex2, 0, 2)],
            ['row' => '1B0', 'cell' => 9, 'value' => substr($hex2, 2, 2)],
            ['row' => '1B0', 'cell' => 10, 'value' => substr($hex2, 4, 2)],
            ['row' => '1B0', 'cell' => 11, 'value' => substr($hex2, 6, 2)],
            ['row' => '1B0', 'cell' => 12, 'value' => substr($hex2, 0, 2)],
            ['row' => '1B0', 'cell' => 13, 'value' => substr($hex2, 2, 2)],
            ['row' => '1B0', 'cell' => 14, 'value' => substr($hex2, 4, 2)],
            ['row' => '1B0', 'cell' => 15, 'value' => substr($hex2, 6, 2)],

            ['row' => '1C0', 'cell' => 0, 'value' => substr($hex2, 0, 2)],
            ['row' => '1C0', 'cell' => 1, 'value' => substr($hex2, 2, 2)],
            ['row' => '1C0', 'cell' => 2, 'value' => substr($hex2, 4, 2)],
            ['row' => '1C0', 'cell' => 3, 'value' => substr($hex2, 6, 2)],
            ['row' => '1C0', 'cell' => 4, 'value' => substr($hex2, 0, 2)],
            ['row' => '1C0', 'cell' => 5, 'value' => substr($hex2, 2, 2)],
            ['row' => '1C0', 'cell' => 6, 'value' => substr($hex2, 4, 2)],
            ['row' => '1C0', 'cell' => 7, 'value' => substr($hex2, 6, 2)],
            ['row' => '1C0', 'cell' => 8, 'value' => substr($hex2, 0, 2)],
            ['row' => '1C0', 'cell' => 9, 'value' => substr($hex2, 2, 2)],
            ['row' => '1C0', 'cell' => 10, 'value' => substr($hex2, 4, 2)],
            ['row' => '1C0', 'cell' => 11, 'value' => substr($hex2, 6, 2)],
            ['row' => '1C0', 'cell' => 12, 'value' => substr($hex2, 0, 2)],
            ['row' => '1C0', 'cell' => 13, 'value' => substr($hex2, 2, 2)],
            ['row' => '1C0', 'cell' => 14, 'value' => substr($hex2, 4, 2)],
            ['row' => '1C0', 'cell' => 15, 'value' => substr($hex2, 6, 2)],

            ['row' => '1D0', 'cell' => 0, 'value' => substr($hex2, 0, 2)],
            ['row' => '1D0', 'cell' => 1, 'value' => substr($hex2, 2, 2)],
            ['row' => '1D0', 'cell' => 2, 'value' => substr($hex2, 4, 2)],
            ['row' => '1D0', 'cell' => 3, 'value' => substr($hex2, 6, 2)],
            ['row' => '1D0', 'cell' => 4, 'value' => substr($hex2, 0, 2)],
            ['row' => '1D0', 'cell' => 5, 'value' => substr($hex2, 2, 2)],
            ['row' => '1D0', 'cell' => 6, 'value' => substr($hex2, 4, 2)],
            ['row' => '1D0', 'cell' => 7, 'value' => substr($hex2, 6, 2)],
            ['row' => '1D0', 'cell' => 8, 'value' => substr($hex2, 0, 2)],
            ['row' => '1D0', 'cell' => 9, 'value' => substr($hex2, 2, 2)],
            ['row' => '1D0', 'cell' => 10, 'value' => substr($hex2, 4, 2)],
            ['row' => '1D0', 'cell' => 11, 'value' => substr($hex2, 6, 2)],
            ['row' => '1D0', 'cell' => 12, 'value' => substr($hex2, 0, 2)],
            ['row' => '1D0', 'cell' => 13, 'value' => substr($hex2, 2, 2)],
            ['row' => '1D0', 'cell' => 14, 'value' => substr($hex2, 4, 2)],
            ['row' => '1D0', 'cell' => 15, 'value' => substr($hex2, 6, 2)],

            ['row' => '1E0', 'cell' => 0, 'value' => substr($hex2, 0, 2)],
            ['row' => '1E0', 'cell' => 1, 'value' => substr($hex2, 2, 2)],
            ['row' => '1E0', 'cell' => 2, 'value' => substr($hex2, 4, 2)],
            ['row' => '1E0', 'cell' => 3, 'value' => substr($hex2, 6, 2)],
            ['row' => '1E0', 'cell' => 4, 'value' => substr($hex2, 0, 2)],
            ['row' => '1E0', 'cell' => 5, 'value' => substr($hex2, 2, 2)],
            ['row' => '1E0', 'cell' => 6, 'value' => substr($hex2, 4, 2)],
            ['row' => '1E0', 'cell' => 7, 'value' => substr($hex2, 6, 2)],
            ['row' => '1E0', 'cell' => 8, 'value' => substr($hex2, 0, 2)],
            ['row' => '1E0', 'cell' => 9, 'value' => substr($hex2, 2, 2)],
            ['row' => '1E0', 'cell' => 10, 'value' => substr($hex2, 4, 2)],
            ['row' => '1E0', 'cell' => 11, 'value' => substr($hex2, 6, 2)],
            ['row' => '1E0', 'cell' => 12, 'value' => substr($hex2, 0, 2)],
            ['row' => '1E0', 'cell' => 13, 'value' => substr($hex2, 2, 2)],
            ['row' => '1E0', 'cell' => 14, 'value' => substr($hex2, 4, 2)],
            ['row' => '1E0', 'cell' => 15, 'value' => substr($hex2, 6, 2)],
            
            ['row' => '1F0', 'cell' => 0, 'value' => substr($hex2, 0, 2)],
            ['row' => '1F0', 'cell' => 1, 'value' => substr($hex2, 2, 2)],
            ['row' => '1F0', 'cell' => 2, 'value' => substr($hex2, 4, 2)],
            ['row' => '1F0', 'cell' => 3, 'value' => substr($hex2, 6, 2)],
            ['row' => '1F0', 'cell' => 4, 'value' => substr($hex2, 0, 2)],
            ['row' => '1F0', 'cell' => 5, 'value' => substr($hex2, 2, 2)],
            ['row' => '1F0', 'cell' => 6, 'value' => substr($hex2, 4, 2)],
            ['row' => '1F0', 'cell' => 7, 'value' => substr($hex2, 6, 2)],
            ['row' => '1F0', 'cell' => 8, 'value' => substr($hex2, 0, 2)],
            ['row' => '1F0', 'cell' => 9, 'value' => substr($hex2, 2, 2)],
            ['row' => '1F0', 'cell' => 10, 'value' => substr($hex2, 4, 2)],
            ['row' => '1F0', 'cell' => 11, 'value' => substr($hex2, 6, 2)],
            ['row' => '1F0', 'cell' => 12, 'value' => substr($hex2, 0, 2)],
            ['row' => '1F0', 'cell' => 13, 'value' => substr($hex2, 2, 2)],
            ['row' => '1F0', 'cell' => 14, 'value' => substr($hex2, 4, 2)],
            ['row' => '1F0', 'cell' => 15, 'value' => substr($hex2, 6, 2)],

            ['row' => '200', 'cell' => 0, 'value' => substr($hex2, 0, 2)],
            ['row' => '200', 'cell' => 1, 'value' => substr($hex2, 2, 2)],
            ['row' => '200', 'cell' => 2, 'value' => substr($hex2, 4, 2)],
            ['row' => '200', 'cell' => 3, 'value' => substr($hex2, 6, 2)],
            ['row' => '200', 'cell' => 4, 'value' => substr($hex2, 0, 2)],
            ['row' => '200', 'cell' => 5, 'value' => substr($hex2, 2, 2)],
            ['row' => '200', 'cell' => 6, 'value' => substr($hex2, 4, 2)],
            ['row' => '200', 'cell' => 7, 'value' => substr($hex2, 6, 2)],
            ['row' => '200', 'cell' => 8, 'value' => substr($hex2, 0, 2)],
            ['row' => '200', 'cell' => 9, 'value' => substr($hex2, 2, 2)],
            ['row' => '200', 'cell' => 10, 'value' => substr($hex2, 4, 2)],
            ['row' => '200', 'cell' => 11, 'value' => substr($hex2, 6, 2)],
            ['row' => '200', 'cell' => 12, 'value' => substr($hex2, 0, 2)],
            ['row' => '200', 'cell' => 13, 'value' => substr($hex2, 2, 2)],
            ['row' => '200', 'cell' => 14, 'value' => substr($hex2, 4, 2)],
            ['row' => '200', 'cell' => 15, 'value' => substr($hex2, 6, 2)],



            
        ];
    }
}
